version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - GATEWAY_PORT=3001
      - BACKEND_URL=http://backend:5000
      - PAYMENT_URL=http://payment-service:5001
    env_file:
      - ./api-gateway/.env
    depends_on:
      - backend
      - payment-service
    networks:
      - app-network

  backend:
    build: ./services/AuthService
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./services/AuthService/.env
    depends_on:
      - db
      - redis
    networks:
      - app-network

  payment-service:
    build: ./services/PaymentService
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    env_file:
      - ./services/PaymentService/.env
    networks:
      - app-network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: windosutils_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge